// import { Metadata } from "next";

// export const metadata: Metadata = {
//   title: "Hotel Sudarshan",
//   description: "Generated by Sagar Sharma",
// };
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hotel Sudarshan | Luxury Rooms & Suites in Ayodhya ",
  description: "Experience unparalleled luxury at Hotel Sudarshan. Book deluxe rooms, family suites, and enjoy world-class amenities in Ayodhya . Your comfort is our priority!",
  openGraph: {
    title: "Hotel Sudarshan | Luxury Rooms & Suites in Ayodhya",
    description: "Stay at Hotel Sudarshan for exceptional hospitality, stunning rooms, and top-notch services in Ayodhya. Perfect for vacations or business trips.",
    url: "https://hotelsudarshan.com",
    siteName: "Hotel Sudarshan",
    type: "website",
    images: [
      {
        url: "/images/og-image.jpg", 
        width: 1200,
        height: 630,
        alt: "Hotel Sudarshan - Luxury Rooms & Suites",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@SudarshanAyd",
    title: "Hotel Sudarshan | Luxury Rooms & Suites in Ayodhya",
    description: "Discover the elegance of Hotel Sudarshan. Book your stay now for luxury, comfort, and unmatched hospitality.",
    images: ["/images/twitter-image.jpg"], 
  },
  alternates: {
    canonical: "https://hotelsudarshan.com", 
  },
};
